swagger: "2.0"
info:
  version: 1.0.0
  title: modern-express
  description: How do i node in late 2017
basePath: /
tags:
  - name: User
    description: Authentication and user data
  - name: Project
    description: A project contains many groups of tasks and a list of members
  - name: Company
    description: A company represents a group of users or an external contact
  - name: Panel
    description: A panel contains a group of tasks

host: localhost:8080

securityDefinitions:
  bearer:
    type: apiKey
    name: Authorization
    in: header

security:
  - bearer: []

schemes: 
  - http

consumes:
  - application/json
produces:
  - application/json

responses:
  UnauthorizedError:
    description: Access token is missing or invalid
    schema:
      $ref: '#/definitions/ErrorMessage'
  NotFoundError:
    description: Entity not found
    schema:
      $ref: '#/definitions/ErrorMessage'
  PermissionError:
    description: Permission denied
    schema:
      $ref: '#/definitions/ErrorMessage'

definitions:
  ErrorMessage:
    type: object
    properties:
      error:
        type: string
      status:
        type: number
      name:
        type: string
  Page:
    type: object
    title: Page
    properties:
      size:
        type: integer
      page:
        type: integer
      totalPages:
        type: integer
      totalElements:
        type: integer
      first:
        type: boolean
      last: 
        type: boolean
  UserFromDB:
    type: object
    title: UserFromDB
    properties:
      _id:
        type: string
      __v:
        type: number
      full_name:
        type: string
        description: name and surname
      email:
        type: string
        description: email adress
      created_at:
        type: string
        format: date-time
        description: date when the user was created
      roles:
        type: array
        items:
          type: string
          enum: 
            - DEVELOPER
            - ADMIN
            - CUSTOMER
      activated:
        type: boolean
        default: true
      company:
        $ref: '#/definitions/Company'
  UserFromClient:
    type: object
    title: UserFromClient
    required:
      - full_name
      - email
      - password
      - roles
    properties:
      password:
        type: string
        description: will be hashed securely
      full_name:
        type: string
        description: name and surname
      email:
        type: string
        description: email adress
      roles:
        type: array
        items:
          type: string
          enum: 
            - DEVELOPER
            - ADMIN
            - CUSTOMER
      activated:
        type: boolean
        default: true
      company:
        $ref: '#/definitions/Company'
  Project:
    type: object
    title: Project
    required:
      - name
    properties:
      name:
        type: string
      completedEstimated:
        type: integer
        minimum: 0
        maximum: 100
      status:
        type: string
        enum: 
          - ACTIVED
          - PAUSED
          - FINISHED
      budget:
        type: object
        properties:
          ownAmount:
            type: number
          hours:
            type: number
          billingDate:
            type: string
            format: date-time
          startDate:
            type: string
            format: date-time
          endDate:
            type: string
            format: date-time
  Company:
    type: object
    title: Company
    required:
      - name
    properties:
      name:
        type: string
      address:
        type: string
      type:
        type: string
        enum:
          - INTERNAL
          - CONTACT
  Panel:
    type: object
    title: Panel
    required:
      - name
    properties:
      name: 
        type: string
      hidden:
        type: boolean
      orderPosition:
        type: integer
        minimum: 0
      defaultTaskStatus:
        type: string
        enum: 
          - PENDING
          - ACTIVE
          - COMPLETED

paths:
  /user:
    get:
      tags:
        - User
      description: Fetch all users
      parameters:
        - name: page
          in: query
          type: integer
        - name: limit
          in: query
          type: integer
      responses:
        200:
          description: Get a list of all users in the system
          schema:
            allOf:
              - properties:
                  docs:
                    type: array
                    items:
                      $ref: '#/definitions/UserFromDB'
              - $ref: '#/definitions/Page'
        401:
          $ref: '#/responses/UnauthorizedError'
        403:
          $ref: '#/responses/PermissionError'
    post:
      tags: 
        - User
      description: Create a new user
      parameters: 
        - name: user
          in: body
          required: true
          schema:
            $ref: '#/definitions/UserFromClient'
      responses:
        201:
          description: OK
          schema:
            $ref: '#/definitions/UserFromDB'
        401:
          $ref: '#/responses/UnauthorizedError'
        403:
          $ref: '#/responses/UnauthorizedError'
  /user/authenticate:
    post:
      tags:
        - User
      description: Log user and receive a token
      parameters:
        - name: credentials
          in: body
          description: credentials of the user
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        200:
          description: OK
        401:
          $ref: '#/responses/UnauthorizedError'
  /user/me:
    get:
      tags:
        - User
      description: Get the current user
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/UserFromDB'
        401:
          $ref: '#/responses/UnauthorizedError'
    put:
      tags:
        - User
      description: Update the current user
      parameters: 
        - name: user
          in: body
          required: true
          schema:
            $ref: '#/definitions/UserFromClient'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/UserFromDB'
        404:
          $ref: '#/responses/NotFoundError'
        401:
          $ref: '#/responses/UnauthorizedError'
  /user/{id}:
    get:
      tags:
        - User
      description: Fetch a single user
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the user to fetch
          type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/UserFromDB'
        401:
          $ref: '#/responses/UnauthorizedError'
        404:
          $ref: '#/responses/NotFoundError'
    put:
      tags: 
        - User
      description: Updates and returns a user by id
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the user to fetch
          type: string
        - name: user
          in: body
          required: true
          schema:
            $ref: '#/definitions/UserFromClient'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/UserFromDB'
        401:
          $ref: '#/responses/UnauthorizedError'
        404:
          $ref: '#/responses/NotFoundError'
    delete:
      tags: 
        - User
      description: deletes a user by id (does not return the deleted user)
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the user to fetch
          type: string
      responses:
        200:
          description: OK
        401:
          $ref: '#/responses/UnauthorizedError'
        404:
          $ref: '#/responses/NotFoundError'
  /project:
    get:
      tags: 
        - Project
      parameters:
        - name: page
          in: query
          type: integer
        - name: limit
          in: query
          type: integer
      description: Fetch all projects
      responses: 
        200:
          description: OK
          schema:
            allOf:
              - properties:
                  docs:
                    type: array
                    items:
                      $ref: '#/definitions/Project'
              - $ref: '#/definitions/Page'
        401:
          $ref: '#/responses/UnauthorizedError'
        403:
          $ref: '#/responses/PermissionError'
    post:
      tags:
        - Project
      description: Create a new project
      parameters: 
        - name: project
          in: body
          required: true
          schema:
            $ref: '#/definitions/Project'
      responses:
        200:
          description: OK
        401:
          $ref: '#/responses/UnauthorizedError'
        403:
          $ref: '#/responses/PermissionError'
  /project/{id}:
    get:
      tags:
        - Project
      description: Get project by id
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the project to fetch
          type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Project'
        401:
          $ref: '#/responses/UnauthorizedError'
        403:
          $ref: '#/responses/PermissionError'   
    put:
      tags:
        - Project
      description: Edit a project
      parameters: 
        - name: project
          in: body
          required: true
          schema:
            $ref: '#/definitions/Project'
        - name: id
          in: path
          required: true
          description: The id of the project to edit
          type: string
      responses:
        200:
          description: OK
        401:
          $ref: '#/responses/UnauthorizedError'
        403:
          $ref: '#/responses/PermissionError'
    delete:
      tags:
        - Project
      description: Delete project by id
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the project to delete
          type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Project'
        401:
          $ref: '#/responses/UnauthorizedError'
        403:
          $ref: '#/responses/PermissionError'
  /company:
    get:
      tags: 
        - Company
      parameters:
        - name: page
          in: query
          type: integer
        - name: limit
          in: query
          type: integer
        - name: sort
          in: query
          type: string
      description: Fetch all companies
      responses: 
        200:
          description: OK
          schema:
            allOf:
              - properties:
                  docs:
                    type: array
                    items:
                      $ref: '#/definitions/Company'
              - $ref: '#/definitions/Page'
        401:
          $ref: '#/responses/UnauthorizedError'
        403:
          $ref: '#/responses/PermissionError'
    post:
      tags:
        - Company
      description: Create a new company
      parameters: 
        - name: company
          in: body
          required: true
          schema:
            $ref: '#/definitions/Company'
      responses:
        200:
          description: OK
        401:
          $ref: '#/responses/UnauthorizedError'
        403:
          $ref: '#/responses/PermissionError'
  /company/{id}:
    get:
      tags:
        - Company
      description: Get Company by id
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the Company to fetch
          type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Company'
        401:
          $ref: '#/responses/UnauthorizedError'
        403:
          $ref: '#/responses/PermissionError'   
    put:
      tags:
        - Company
      description: Edit a Company
      parameters: 
        - name: Company
          in: body
          required: true
          schema:
            $ref: '#/definitions/Company'
        - name: id
          in: path
          required: true
          description: The id of the Company to edit
          type: string
      responses:
        200:
          description: OK
        401:
          $ref: '#/responses/UnauthorizedError'
        403:
          $ref: '#/responses/PermissionError'
    delete:
      tags:
        - Company
      description: Delete Company by id
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the Company to delete
          type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Company'
        401:
          $ref: '#/responses/UnauthorizedError'
        403:
          $ref: '#/responses/PermissionError'
  /panel:
    get:
      tags: 
        - Panel
      parameters:
        - name: page
          in: query
          type: integer
        - name: limit
          in: query
          type: integer
      description: Fetch all companies
      responses: 
        200:
          description: OK
          schema:
            allOf:
              - properties:
                  docs:
                    type: array
                    items:
                      $ref: '#/definitions/Panel'
              - $ref: '#/definitions/Page'
        401:
          $ref: '#/responses/UnauthorizedError'
        403:
          $ref: '#/responses/PermissionError'
    post:
      tags:
        - Panel
      description: Create a new Panel
      parameters: 
        - name: Panel
          in: body
          required: true
          schema:
            $ref: '#/definitions/Panel'
      responses:
        200:
          description: OK
        401:
          $ref: '#/responses/UnauthorizedError'
        403:
          $ref: '#/responses/PermissionError'
  /panel/{id}:
    get:
      tags:
        - Panel
      description: Get Panel by id
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the Panel to fetch
          type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Panel'
        401:
          $ref: '#/responses/UnauthorizedError'
        403:
          $ref: '#/responses/PermissionError'   
    put:
      tags:
        - Panel
      description: Edit a Panel
      parameters: 
        - name: Panel
          in: body
          required: true
          schema:
            $ref: '#/definitions/Panel'
        - name: id
          in: path
          required: true
          description: The id of the Panel to edit
          type: string
      responses:
        200:
          description: OK
        401:
          $ref: '#/responses/UnauthorizedError'
        403:
          $ref: '#/responses/PermissionError'
    delete:
      tags:
        - Panel
      description: Delete Panel by id
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the Panel to delete
          type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Panel'
        401:
          $ref: '#/responses/UnauthorizedError'
        403:
          $ref: '#/responses/PermissionError'